import jsPDF from "jspdf";

export function generateDossier() {
  const doc = new jsPDF();

  doc.setFontSize(20);

  doc.text(
    "Karnataka State Police",
    20,
    20
  );

  doc.setFontSize(16);

  doc.text(
    "NeuroBytes AI Investigation Dossier",
    20,
    35
  );

  doc.setFontSize(12);

  doc.text(
    "Case Summary:",
    20,
    55
  );

  doc.text(
    "Theft reported in Mysuru South. Two suspects identified.",
    20,
    65
  );

  doc.text(
    "Risk Score: 84/100",
    20,
    85
  );

  doc.text(
    "Evidence:",
    20,
    105
  );

  doc.text(
    "FIR-2026-001",
    25,
    115
  );

  doc.text(
    "FIR-2026-003",
    25,
    125
  );

  doc.text(
    "Recommended Leads:",
    20,
    145
  );

  doc.text(
    "- Repeat offender match detected",
    25,
    155
  );

  doc.text(
    "- Vehicle linked to another FIR",
    25,
    165
  );

  doc.text(
    "Generated by NeuroBytes KSP OS",
    20,
    200
  );

  doc.save("Investigation_Dossier.pdf");
}